name: model-training
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: iterative/setup-cml@v1
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip3 install torch torchvision torchaudio
          pip3 install pandas
          pip3 install scikit-learn
          pip3 install matplotlib
          python evaluate_data.py
          python train.py
          cat result_pytorch.txt >> results.md
          cml-send-comment results.md
